services:
  db:
    container_name: postgres-course
    image: postgres:latest
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  db: